---
nodes:
  compute:
    hostname: dl-compute
    count: 2
    cpu: 1
    memory: 1024
  storage:
    hostname: dl-storage
    count: 2
    cpu: 1
    memory: 1024
    disk_size: 10
    disk_count: 4
  loadbalancer:
    hostname: dl-lb
    count: 2
    cpu: 1
    memory: 1024
  automation:
    hostname: dl-airflow
    count: 1
    cpu: 1
    memory: 1024
vips:
  minio_vip:
    hostname: dl-minio-vip
    count: 1
support_user: support
ip:
  network: '192.168.3'
  start: 20
  domain: 'abccorp.local'
bridge: enp6s0f0
software:
  box: bento/ubuntu-24.04
  minio: latest
  spark: 3.5.5
  airflow: 3.0.1
